"""Store zygosity instead of alleles in Observation model

Revision ID: 1b7581fb6db9
Revises: 200de898ae9f
Create Date: 2013-04-04 11:35:32.568953

"""

# revision identifiers, used by Alembic.
revision = '1b7581fb6db9'
down_revision = '200de898ae9f'

from alembic import op
from sqlalchemy import sql
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # https://bitbucket.org/zzzeek/alembic/issue/89/opadd_column-and-opdrop_column-should
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        has_zygosity_type = context.bind.execute(
            "select exists (select 1 from pg_type "
            "where typname='zygosity')").scalar()
        if not has_zygosity_type:
            op.execute("CREATE TYPE zygosity AS ENUM ('heterozygous', 'homozygous')")

    op.add_column('observation', sa.Column('zygosity', sa.Enum('heterozygous', 'homozygous', name='zygosity'), nullable=True))

    # https://alembic.readthedocs.org/en/latest/ops.html#alembic.operations.Operations.execute
    observation = sql.table('observation',
                            sql.column('alleles', sa.INTEGER()),
                            sql.column('zygosity', sa.Enum('heterozygous', 'homozygous', name='zygosity')))
    op.execute(observation.update().where(observation.c.alleles == op.inline_literal(1)).values({'zygosity': 'heterozygous'}))
    op.execute(observation.update().where(observation.c.alleles == op.inline_literal(2)).values({'zygosity': 'homozygous'}))

    op.drop_column('observation', u'alleles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column(u'alleles', sa.INTEGER(), nullable=True))

    # https://alembic.readthedocs.org/en/latest/ops.html#alembic.operations.Operations.execute
    observation = sql.table('observation',
                            sql.column('alleles', sa.INTEGER()),
                            sql.column('zygosity', sa.Enum('heterozygous', 'homozygous', name='zygosity')))
    op.execute(observation.update().where(observation.c.zygosity == op.inline_literal('heterozygous')).values({'alleles': 1}))
    op.execute(observation.update().where(observation.c.zygosity == op.inline_literal('homozygous')).values({'alleles': 2}))

    op.drop_column('observation', 'zygosity')
    ### end Alembic commands ###
