"""Add sample groups

Revision ID: 1c15bafd311a
Revises: 52c2d8ff8e6f
Create Date: 2015-08-12 17:58:22.640975

"""

# revision identifiers, used by Alembic.
revision = '1c15bafd311a'
down_revision = '52c2d8ff8e6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('group_membership',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='CASCADE')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_membership')
    op.drop_table('group')
    ### end Alembic commands ###
