"""Add variation parameters

Revision ID: 1e6d5f30aa47
Revises: fa54b116549
Create Date: 2013-03-13 20:46:12.330468

"""

# revision identifiers, used by Alembic.
revision = '1e6d5f30aa47'
down_revision = 'fa54b116549'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('prefer_genotype_likelihoods', sa.Boolean(), nullable=True))
    op.add_column('variation', sa.Column('skip_filtered', sa.Boolean(), nullable=True))
    op.add_column('variation', sa.Column('use_genotypes', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation', 'use_genotypes')
    op.drop_column('variation', 'skip_filtered')
    op.drop_column('variation', 'prefer_genotype_likelihoods')
    ### end Alembic commands ###
