"""Remove exclude samples from Annotation model

Revision ID: 200de898ae9f
Revises: 2186ab26ae31
Create Date: 2013-03-26 13:24:22.008694

"""

# revision identifiers, used by Alembic.
revision = '200de898ae9f'
down_revision = '2186ab26ae31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'exclude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'exclude',
    sa.Column(u'annotation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], [u'annotation.id'], name=u'exclude_annotation_id_fkey'),
    sa.ForeignKeyConstraint(['sample_id'], [u'sample.id'], name=u'exclude_sample_id_fkey'),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###
