"""Generic column names for task info

Revision ID: 2235f4fee460
Revises: 5aeb8027407e
Create Date: 2013-01-18 11:02:27.090033

"""

# revision identifiers, used by Alembic.
revision = '2235f4fee460'
down_revision = '5aeb8027407e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation', u'written', name=u'task_done', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('annotation', u'write_task_uuid', name=u'task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    op.alter_column('coverage', u'imported', name=u'task_done', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('coverage', u'import_task_uuid', name=u'task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    op.alter_column('variation', u'imported', name=u'task_done', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('variation', u'import_task_uuid', name=u'task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation', u'task_done', name=u'written', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('annotation', u'task_uuid', name=u'write_task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    op.alter_column('coverage', u'task_done', name=u'imported', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('coverage', u'task_uuid', name=u'import_task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    op.alter_column('variation', u'task_done', name=u'imported', existing_type=sa.Boolean(), existing_nullable=True)
    op.alter_column('variation', u'task_uuid', name=u'import_task_uuid', existing_type=sa.String(length=36), existing_nullable=True)
    ### end Alembic commands ###
