"""Add query frequencies

Revision ID: 46f0145e85d9
Revises: 1c15bafd311a
Create Date: 2015-08-13 18:13:56.035722

"""

# revision identifiers, used by Alembic.
revision = '46f0145e85d9'
down_revision = '1c15bafd311a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('query_membership',
    sa.Column('query_frequency_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_frequency_id'], ['query_frequency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ondelete='CASCADE')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_membership')
    op.drop_table('query_frequency')
    ### end Alembic commands ###
