"""Index on Observation.variation and Region.coverage

Revision ID: 556a06cce259
Revises: 1b7581fb6db9
Create Date: 2013-04-05 09:10:12.972174

"""

# revision identifiers, used by Alembic.
revision = '556a06cce259'
down_revision = '1b7581fb6db9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_observation_variation_id', 'observation', ['variation_id'])
    op.create_index('ix_region_coverage_id', 'region', ['coverage_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observation_variation_id')
    op.drop_index('ix_region_coverage_id')
    ### end Alembic commands ###
