"""Initial schema

Revision ID: 5aeb8027407e
Revises: None
Create Date: 2013-01-18 10:57:27.507624

"""

# revision identifiers, used by Alembic.
revision = '5aeb8027407e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
