"""Add notes to Sample and email to User

Revision ID: 9020798ee31
Revises: 556a06cce259
Create Date: 2013-04-09 09:39:55.250489

"""

# revision identifiers, used by Alembic.
revision = '9020798ee31'
down_revision = '556a06cce259'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('sample', 'notes')
    ### end Alembic commands ###
