"""Cascade delete on user to tokens

Revision ID: a7913ae782d
Revises: 5290d5494cb2
Create Date: 2013-05-30 15:23:38.184773

"""

# revision identifiers, used by Alembic.
revision = 'a7913ae782d'
down_revision = '5290d5494cb2'

from alembic import op
import sqlalchemy as sa


# https://groups.google.com/forum/?fromgroups#!topic/sqlalchemy-alembic/ftGwxOuwfls


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    insp = Inspector.from_engine(op.get_bind())
    fks = insp.get_foreign_keys('token')
    for fk in fks:
        if fk['constrained_columns'] != 'user_id':
            pass
        op.drop_constraint(fk['name'], 'token')
        op.create_foreign_key(fk['name'], 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    insp = Inspector.from_engine(op.get_bind())
    fks = insp.get_foreign_keys('token')
    for fk in fks:
        if fk['constrained_columns'] != 'user_id':
            pass
        op.drop_constraint(fk['name'], 'token')
        op.create_foreign_key(fk['name'], 'token', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
