"""Foreign keys not null in all models

Revision ID: d23512f46a2
Revises: a7913ae782d
Create Date: 2013-05-30 16:37:33.504478

"""

# revision identifiers, used by Alembic.
revision = 'd23512f46a2'
down_revision = 'a7913ae782d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation', u'original_data_source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('annotation', u'annotated_data_source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coverage', u'data_source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coverage', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('data_source', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('observation', u'variation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('region', u'coverage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_frequency', u'annotation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_frequency', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('variation', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('variation', u'data_source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variation', u'data_source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('variation', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample_frequency', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample_frequency', u'annotation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('region', u'coverage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('observation', u'variation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('data_source', u'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coverage', u'sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coverage', u'data_source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('annotation', u'annotated_data_source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('annotation', u'original_data_source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
