"""Add allele column to Observation model

Revision ID: fa54b116549
Revises: 2235f4fee460
Create Date: 2013-01-24 16:57:41.770694

"""

# revision identifiers, used by Alembic.
revision = 'fa54b116549'
down_revision = '2235f4fee460'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('alleles', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation', 'alleles')
    ### end Alembic commands ###
